### ISSUE TITLE
how to create a rotated box?

### ISSUE THREAD

**Issue by Cbanyungong** [chinakook/labelImg2#1]
Dear chinakook.
    I found your code could not be used to create a rotated box. Could you please explain how to get a rotated box?

**Comment by chinakook** [comment]
The button is on the right hand of the normal box button.

**Comment by Cbanyungong** [comment]
I use the button,but the angle I get always is 0.What is the wrong with me? @chinakook

**Comment by chinakook** [comment]
Drag the vertex when it becomes to little rect with right mouse.

**Comment by Cbanyungong** [comment]
Your work is excellent!Thanks for your code and instruction.I get the correct rotated box.

**Comment by chinakook** [comment]
No problem.
